aliases: # optional: add aliases here in the format of <NSA ID>: <alias>
  b023adfefd82147a: LittleBit670 # example
ntfy:
  enabled: true # if false, no push notifications will be sent
  server: "https://ntfy.sh" # The base URL of your ntfy server (use a self-hosted one or the public one)
  topic: "your_unique_switch_friend_topic" # REQUIRED: The topic name to which the script will publish and your app is subscribed
  sendtest: 'off' # set to 'unwatched' or 'watched' to send a test notification on next run, must be reset to off
watched: # this field is optional
- LittleBit # example of nickname
- b023adfefd82147a # example of NSA ID
# above is the list of watched friends; you can add watches by nickname or NSA ID
# NSA IDs can be obtained using the command "nxapi nso friends" or with the nxapi desktop app
windowsmode: false # this must be true for Windows users; not needed for MacOS or Linux
watchedonly: true # if true, only watched friends will trigger a notification; the watched list is required if this is true